### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by reachyou91** [themains/domain_knowledge#1]
I keep having type error when using phishtank, shallalist, toulouse. Here are the errors below.
`
df_toulouse = pred_toulouse(df, domain_names = 'resolved_domain')
Downloading Toulouse model data from the server (toulouse_cat_lstm_others_2017.h5)...
 98%|█████████▊| 1600.0/1631.5 [00:00<00:00, 12499.23KB/s]
Downloading Toulouse vocab data from the server (toulouse_cat_vocab_others_2017.csv)...
 96%|█████████▌| 64.0/66.625 [00:00<00:00, 8090.28KB/s]
Downloading Toulouse names data from the server (toulouse_cat_names_others_2017.csv)...
100%|█████████▉| 64.0/64.080078125 [00:00<?, ?KB/s]
Loading Toulouse model, vocab and names data file...
Traceback (most recent call last):

  File "<ipython-input-24-901daa57a55f>", line 1, in <module>
    df_toulouse = pred_toulouse(df, domain_names = 'resolved_domain')

  File "C:\Users\Simon\anaconda3\lib\site-packages\pydomains\pred_toulouse.py", line 100, in pred_toulouse
    df[col_domain] = df[domain_names].apply(lambda c: url2domain(c, exclude_subdomains=['www']))

  File "C:\Users\Simon\anaconda3\lib\site-packages\pandas\core\series.py", line 4356, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()

  File "C:\Users\Simon\anaconda3\lib\site-packages\pandas\core\apply.py", line 1036, in apply
    return self.apply_standard()

  File "C:\Users\Simon\anaconda3\lib\site-packages\pandas\core\apply.py", line 1092, in apply_standard
    mapped = lib.map_infer(

  File "pandas\_libs\lib.pyx", line 2859, in pandas._libs.lib.map_infer

  File "C:\Users\Simon\anaconda3\lib\site-packages\pydomains\pred_toulouse.py", line 100, in <lambda>
    df[col_domain] = df[domain_names].apply(lambda c: url2domain(c, exclude_subdomains=['www']))

  File "C:\Users\Simon\anaconda3\lib\site-packages\pydomains\utils.py", line 66, in url2domain
    tld = tldextract.extract(url)

  File "C:\Users\Simon\anaconda3\lib\site-packages\tldextract\tldextract.py", line 296, in extract
    return TLD_EXTRACTOR(url, include_psl_private_domains=include_psl_private_domains)

  File "C:\Users\Simon\anaconda3\lib\site-packages\tldextract\tldextract.py", line 216, in __call__
    SCHEME_RE.sub("", url)

TypeError: expected string or bytes-like object
`

Is there any difference in function between domz_cat and the other three?

**Comment by soodoku** [comment]
can you share what you were passing in the df?

diff. b/w functions = different data sources (which affects what classes you will see, etc.) and diff. models (we built one for each data source). 

we are in the middle of doing a v2 where we use more data per domain. it will lead to a more accurate but more expensive prediction function.

**Comment by soodoku** [comment]
by the way, you should be opening this issue at: https://github.com/themains/pydomains

**Comment by reachyou91** [comment]
Hello, Thank you for your fast reply and I apologize for misplacing to open my issue. Let me open the issue to my domains with detailed information that I have.
